language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
    - ccache
    - swig
matrix:
 allow_failures:
    - python: 3.4
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
install:
  - pip install cython
  - pip install -r travis-ci-requirements.txt
  - python setup.py develop
before_script:
  - cp .coveragerc integrationtests
  - cd integrationtests
script:
  - coverage run -m nose.core codetools -v
  # Do not run the integration tests (see issue #21)
  # - coverage run -a -m nose.core integrationtests/ -v
after_success:
  - pip install codecov
  - codecov
