language: generic
dist: xenial
services:
  - xvfb

env:
  global:
    - INSTALL_EDM_VERSION=2.0.0
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - env: RUNTIME=2.7
    - env: RUNTIME=3.5
    - env: RUNTIME=3.6
    - os: osx
      env: RUNTIME=2.7
    - os: osx
      env: RUNTIME=3.5
    - os: osx
      env: RUNTIME=3.6
  fast_finish: true

cache:
  directories:
    - "~/.cache"

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ./install-edm-osx.sh; export PATH="${PATH}:/usr/local/bin"; fi
  - edm install -y wheel click coverage
install:
  - edm run -- python etstool.py install --runtime=${RUNTIME} || exit
script:
  - edm run -- python etstool.py test --runtime=${RUNTIME} || exit
  # Building docs on python 3 is broken at the moment
  # - edm run -- python etstool.py docs --runtime=${RUNTIME} || exit
  # Do not run the integration tests (see issue #21)
  # - cp .coveragerc integrationtests
  # - cd integrationtests
  # - coverage run -a -m nose.core integrationtests/ -v

after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov

notifications:
  email:
    - travis-ci@enthought.com
