name: Test with EDM

on: [pull_request, workflow_dispatch]

env:
  INSTALL_EDM_VERSION: 3.3.1

jobs:

  test-with-edm:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}

      - name: Install click to the default EDM environment
        run: edm install -y click wheel

      - name: Install codetools
        run: edm run -- python etstool.py install

      - name: Run tests
        run: edm run -- python etstool.py test
